// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeShare.Data;

#nullable disable

namespace RecipeShare.Migrations
{
    [DbContext(typeof(RecipeDBContext))]
    partial class RecipeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeShare.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<int>("CookingTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("DietaryTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            CookingTimeMinutes = 20,
                            DietaryTags = "Non-Vegetarian",
                            Ingredients = "Spaghetti, Guanciale (or Pancetta), Eggs, Pecorino Romano, Black Pepper",
                            Steps = "1. Cook spaghetti. 2. Fry guanciale. 3. Whisk eggs, cheese, pepper. 4. Combine with pasta and guanciale.",
                            Title = "Classic Spaghetti Carbonara"
                        },
                        new
                        {
                            RecipeId = 2,
                            CookingTimeMinutes = 45,
                            DietaryTags = "Vegan,Vegetarian,Gluten-Free",
                            Ingredients = "Red lentils, Carrots, Celery, Onion, Garlic, Vegetable broth, Diced tomatoes, Spices",
                            Steps = "1. Sauté aromatics. 2. Add lentils, vegetables, broth, tomatoes. 3. Simmer until lentils are tender.",
                            Title = "Vegan Lentil Soup"
                        },
                        new
                        {
                            RecipeId = 3,
                            CookingTimeMinutes = 25,
                            DietaryTags = "Non-Vegetarian,Gluten-Free (with Tamari)",
                            Ingredients = "Chicken breast, Broccoli, Bell peppers, Soy sauce, Ginger, Garlic, Rice vinegar, Sesame oil",
                            Steps = "1. Marinate chicken. 2. Stir-fry chicken. 3. Add vegetables and sauce. 4. Serve with rice.",
                            Title = "Quick Chicken Stir-Fry"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
